default:
    - client_class: "openai.AzureOpenAI" # doesn't use the `openai.OpenAI` client class
      # the following are passed to the `AzureOpenAI` client class
      azure_deployment: "gpt-4o" # name of the model
      api_key: "your Azure OpenAI API key" # your Azure OpenAI API key
      azure_endpoint: 'your Azure OpenAI endpoint (typically starts with "https://")' # your Azure OpenAI endpoint (typically starts with "https://")
      api_version: "2024-12-01-preview" # API version, e.g., "2024-10-21"